## 4.3 Unique and other Set Logics

In [2]:
import numpy as np

In [3]:
arr_1 = np.arange(10)
arr_2 = [2,4,9]
np.in1d(arr_1, arr_2)

array([False, False,  True, False,  True, False, False, False, False,  True], dtype=bool)

In [4]:
arr_3 = np.array([1,4,123])
np.in1d(arr_1,arr_3)

array([False,  True, False, False,  True, False, False, False, False, False], dtype=bool)

In [5]:
np.setdiff1d(arr_1,arr_3)

array([0, 2, 3, 5, 6, 7, 8, 9])

In [6]:
np.intersect1d(arr_1,arr_3)

array([1, 4])

In [7]:
np.setxor1d(arr_1,arr_3)

array([  0,   2,   3,   5,   6,   7,   8,   9, 123])

## 4.4 File Input and Output with Arrays

In [8]:
arr = np.arange(100)

In [9]:
np.save('my_array_saved',arr)

In [10]:
np.load('my_array_saved.npy')

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

#### Passing multiple arrays

In [11]:
np.savez('array_archive', a = arr, b = arr)

to load it, assign it to a variable and unpack it

In [12]:
arch = np.load('array_archive.npz')

In [13]:
[i for i in arch]


['a', 'b']

In [14]:
arch['b']

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [15]:
a1,a2 = arch['a'],arch['b']

In [16]:
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

## Random Walk

In [17]:
import random

In [18]:
position = 0
walk = [position]
steps = 10

for i in range(steps):
    step = 1 if random.randint(0,1) else -1
    position +=step
    walk.append(position)

In [19]:
position

2

In [20]:
walk

[0, 1, 2, 1, 0, -1, 0, 1, 2, 1, 2]

In [21]:
draws = np.random.randint(0,2,size = 100)

In [22]:
steps = np.where(draws == 0,-1,1)

In [23]:
steps

array([ 1,  1,  1,  1,  1, -1,  1, -1, -1,  1, -1, -1,  1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1,  1,  1, -1,  1, -1, -1, -1, -1,
       -1,  1, -1, -1,  1,  1, -1,  1,  1, -1,  1,  1,  1,  1,  1, -1,  1,
        1, -1,  1,  1, -1,  1, -1,  1,  1, -1, -1, -1, -1, -1,  1,  1,  1,
       -1, -1, -1,  1, -1,  1,  1, -1,  1, -1,  1,  1,  1,  1,  1, -1,  1,
        1,  1, -1,  1,  1, -1,  1, -1, -1,  1, -1,  1,  1, -1,  1])

In [24]:
walk = steps.cumsum()

In [25]:
(walk>=10).argmax()

0

In [26]:
(walk>=10).argmin()

0

## Simulating several walks

In [27]:
nwalks = 5000
nsteps = 1000

draws = np.random.randint(0,2,size=(nwalks,nsteps))
steps = np.where(draws>0,1,-1)
walks = steps.cumsum(1)

In [28]:
walks

array([[  1,   2,   3, ...,  44,  43,  42],
       [  1,   0,   1, ...,  28,  27,  28],
       [  1,   2,   3, ..., -28, -29, -30],
       ..., 
       [  1,   0,  -1, ..., -48, -49, -50],
       [ -1,   0,  -1, ..., -12, -11, -10],
       [ -1,  -2,  -1, ..., -12, -13, -12]])

In [29]:
walks.max()

113

In [30]:
walks.max(1)

array([47, 53,  7, ...,  5,  8,  1])

In [32]:
walks.max(0)

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  10,  11,
        12,  13,  14,  13,  14,  15,  16,  17,  16,  17,  16,  17,  18,
        17,  18,  17,  18,  19,  18,  19,  20,  19,  20,  21,  22,  21,
        22,  21,  22,  21,  20,  21,  22,  23,  22,  23,  22,  23,  24,
        25,  26,  27,  26,  25,  24,  25,  26,  25,  26,  27,  28,  29,
        30,  29,  28,  27,  28,  27,  28,  29,  28,  29,  30,  29,  30,
        31,  30,  31,  30,  31,  32,  33,  34,  33,  34,  33,  34,  33,
        34,  35,  34,  35,  34,  35,  34,  33,  34,  35,  34,  35,  36,
        35,  34,  35,  36,  37,  36,  37,  36,  37,  38,  39,  40,  41,
        40,  41,  42,  41,  42,  41,  40,  41,  42,  43,  44,  43,  44,
        45,  46,  45,  44,  43,  44,  43,  42,  43,  44,  45,  44,  45,
        46,  47,  48,  47,  48,  49,  48,  49,  48,  49,  50,  51,  50,
        49,  50,  51,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59,
        58,  59,  58,  57,  56,  57,  58,  59,  58,  59,  58,  5